###
### A complete description of a Prefect Deployment for flow 'idealista-to-gcp-pipeline'
###
name: madrid_rent_daily
description: |-
  Scrape idealista listings given search parameters and upload to GCS and BigQuery.

  Args:
      province: The province to search in Spain
      type_search: The type of search to perform (sale, rent or share)
      time_period: The time period to search for.
          - '24': last 24 hours
          - '48': last 48 hours
          - 'week': last week
          - 'month': last month

      bucket_name: The name of the GCS bucket to upload the data to
      dataset_id: The name of the BigQuery dataset to upload the data to
      credentials_path: The path to the GCS credentials
      zone: The zone to search in the province. These zones are defined in
      the idealista website. (default None = search in the whole province)
      batch_size: The number of properties to scrape before uploading to GCS
      (default 30)
      max_execution_time: The maximum time to run the pipeline in seconds
      (default 18 hours)
      testing: Whether to run the pipeline in testing mode (default False)
version: c2d87aa6d096aeeaa96352a1a0ca1fd6
# The work queue that will handle this deployment's runs
work_queue_name: rent
work_pool_name: default-agent-pool
tags:
- rent
parameters:
  zone: madrid
  testing: false
  province: madrid
  dataset_id: idealista_listings
  bucket_name: idealista_data_lake_idealista-scraper-384619
  time_period: 24
  type_search: rent
  credentials_path: ~/.gcp/prefect-agent.json
schedule:
  cron: 0 7 * * *
  timezone: Europe/Madrid
  day_or: true
is_schedule_active: true
infra_overrides: {}

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: idealista-to-gcp-pipeline
manifest_path: null
infrastructure:
  type: process
  env: {}
  labels: {}
  name: null
  command: null
  stream_output: true
  working_dir: null
  _block_document_id: 45cd9ec0-fb60-40c3-96f4-ec0aa71e69eb
  _block_document_name: anonymous-8c24c835-76ea-4c27-b119-3d74eeedfb8e
  _is_anonymous: true
  block_type_slug: process
  _block_type_slug: process
storage: null
path: /home/aarroyo/real_estate_spain
entrypoint: src/flows/idealista_flow.py:idealista_to_gcp_pipeline
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    province:
      title: province
      description: The province to search in Spain
      position: 0
      type: string
    type_search:
      title: type_search
      description: The type of search to perform (sale, rent or share)
      position: 1
      type: string
    time_period:
      title: time_period
      description: |-
        The time period to search for.
        - '24': last 24 hours
        - '48': last 48 hours
        - 'week': last week
        - 'month': last month
      position: 2
      type: string
    bucket_name:
      title: bucket_name
      description: The name of the GCS bucket to upload the data to
      position: 3
      type: string
    dataset_id:
      title: dataset_id
      description: The name of the BigQuery dataset to upload the data to
      position: 4
      type: string
    credentials_path:
      title: credentials_path
      description: The path to the GCS credentials
      position: 5
      type: string
    zone:
      title: zone
      description: The zone to search in the province. These zones are defined in
      position: 6
      type: string
    batch_size:
      title: batch_size
      description: The number of properties to scrape before uploading to GCS
      default: 30
      position: 7
      type: integer
    max_execution_time:
      title: max_execution_time
      description: The maximum time to run the pipeline in seconds
      default: 64800
      position: 8
      type: integer
    testing:
      title: testing
      description: Whether to run the pipeline in testing mode (default False)
      default: false
      position: 9
      type: boolean
  required:
  - province
  - type_search
  - time_period
  - bucket_name
  - dataset_id
  - credentials_path
  definitions: null
timestamp: '2024-01-02T17:42:59.922415+00:00'
